title: "Pete's Complete Auto Service"
description: "Full-service auto repair and maintenance in Plantation, Lauderhill and Tamarac, FL"
phone: "(954) 327-0207"
phone_link: "+19543270207"
facebook: "https://www.facebook.com/petescompleteautoservice/"
address: "Plantation, FL"

# GitHub Pages settings
theme: null
plugins: []
